import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainContent from "@/components/MainContent";
import NewSidebar from "@/components/NewSidebar";
import { SidebarProvider } from "@/context/sidebarContext";
import { QueryProvider } from "@/providers/queryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <SidebarProvider>
            <main className="max-w-[1640px] mx-auto overflow-hidden h-screen text-black flex">
              <NewSidebar />

              {/* <MainContent /> */}
              <div className="w-full h-full">{children}</div>
            </main>
          </SidebarProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
